# Generated by Django 6.0.5 on 2026-05-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('asignacion', 'Asignación de Tarea'), ('comentario', 'Nuevo Comentario'), ('cambio_estado', 'Cambio de Estado'), ('vencimiento', 'Vencimiento Próximo'), ('mencion', 'Mención'), ('sistema', 'Sistema')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('enlace', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
