# Generated by Django 6.0.5 on 2026-05-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('gerente_proyecto', 'Gerente de Proyecto'), ('coordinador', 'Coordinador'), ('tecnico', 'Técnico'), ('colaborador', 'Colaborador'), ('cliente', 'Cliente')], default='colaborador', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Miembro del Proyecto',
                'verbose_name_plural': 'Miembros del Proyecto',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('planificado', 'Planificado'), ('en_curso', 'En Curso'), ('en_pausa', 'En Pausa'), ('en_riesgo', 'En Riesgo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='planificado', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True)),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('presupuesto_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('presupuesto_ejecutado', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('porcentaje_avance', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
