# Generated by Django 6.0.5 on 2026-05-07 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('tipo', models.CharField(choices=[('documento', 'Documento'), ('plano', 'Plano'), ('informe', 'Informe'), ('contrato', 'Contrato'), ('presentacion', 'Presentación'), ('otro', 'Otro')], default='documento', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='proyectos.proyecto')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento del Proyecto',
                'verbose_name_plural': 'Documentos del Proyecto',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
