# Generated by Django 6.0.5 on 2026-05-07 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0002_initial'),
        ('proyectos', '0003_documentoproyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='espacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='espacios.espaciotrabajo'),
        ),
    ]
