# Generated by Django 6.0.5 on 2026-05-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_proyecto_direccion_proyecto_latitud_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidad',
            options={'ordering': ['nombre'], 'verbose_name': 'Unidad Asistencial', 'verbose_name_plural': 'Unidades Asistenciales'},
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='activa',
        ),
        migrations.AddField(
            model_name='unidad',
            name='estado_implementacion',
            field=models.CharField(choices=[('en_implementacion', 'En Implementación'), ('implementada', 'Implementada')], default='en_implementacion', max_length=30),
        ),
        migrations.AddField(
            model_name='unidad',
            name='fecha_implementacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
