# Generated by Django 6.0.5 on 2026-05-07 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_alter_unidad_options_remove_unidad_activa_and_more'),
        ('tareas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades', to='tareas.tarea'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='estado_implementacion',
            field=models.CharField(choices=[('a_implementar', 'A Implementar'), ('en_implementacion', 'En Implementación'), ('implementada', 'Implementada')], default='a_implementar', max_length=30),
        ),
    ]
