# Generated by Django 6.0.5 on 2026-05-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_unidad_tarea_alter_unidad_estado_implementacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='estado_implementacion',
            field=models.CharField(choices=[('a_implementar', 'A IMPLEMENTAR'), ('en_implementacion', 'EN IMPLEMENTACIÓN'), ('implementada', 'IMPLEMENTADA')], default='a_implementar', max_length=30),
        ),
    ]
