# Generated by Django 6.0.5 on 2026-05-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_alter_unidad_estado_implementacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='mostrar_mapa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='plantilla',
            field=models.CharField(choices=[('vacia', 'Vacío'), ('implementacion', 'Implementación')], default='vacia', max_length=20),
        ),
    ]
