# Generated by Django 6.0.5 on 2026-05-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0009_proyecto_mostrar_mapa_proyecto_plantilla'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('mostrar_mapa', models.BooleanField(default=True)),
                ('columnas', models.JSONField(default=list, help_text='Lista de columnas: [{"nombre": ..., "orden": ..., "color": ...}]')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Proyecto',
                'verbose_name_plural': 'Plantillas de Proyecto',
                'ordering': ['nombre'],
            },
        ),
    ]
