# Generated by Django 6.0.5 on 2026-05-11 11:38

from django.db import migrations


COLUMNAS_VACIO = []

COLUMNAS_IMPLEMENTACION = [
    {'nombre': 'SIN IMPLEMENTAR', 'orden': 0, 'color': '#6b7280'},
    {'nombre': 'EN IMPLEMENTACIÓN', 'orden': 1, 'color': '#ef4444'},
    {'nombre': 'IMPLEMENTADA', 'orden': 2, 'color': '#3b82f6'},
]


def seed_plantillas(apps, schema_editor):
    Plantilla = apps.get_model('proyectos', 'PlantillaProyecto')
    Plantilla.objects.get_or_create(
        nombre='Vacío',
        defaults={
            'descripcion': 'Proyecto sin tablero predefinido',
            'mostrar_mapa': False,
            'columnas': COLUMNAS_VACIO,
        }
    )
    Plantilla.objects.get_or_create(
        nombre='Implementación',
        defaults={
            'descripcion': 'Tablero con columnas SIN IMPLEMENTAR, EN IMPLEMENTACIÓN, IMPLEMENTADA + mapa',
            'mostrar_mapa': True,
            'columnas': COLUMNAS_IMPLEMENTACION,
        }
    )


def delete_plantillas(apps, schema_editor):
    Plantilla = apps.get_model('proyectos', 'PlantillaProyecto')
    Plantilla.objects.filter(nombre__in=['Vacío', 'Implementación']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0010_plantillaproyecto'),
    ]

    operations = [
        migrations.RunPython(seed_plantillas, delete_plantillas),
    ]
