# Generated by Django 6.0.5 on 2026-05-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0011_seed_plantillas'),
    ]

    operations = [
        migrations.CreateModel(
            name='UA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('categoria', models.CharField(blank=True, default='', max_length=100)),
                ('departamento', models.CharField(blank=True, default='', max_length=100)),
                ('localidad', models.CharField(blank=True, default='', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'UA - Unidad Asistencial',
                'verbose_name_plural': 'UA - Unidades Asistenciales',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='unidad',
            options={'ordering': ['nombre'], 'verbose_name': 'Unidad Asistencial (deprecated)', 'verbose_name_plural': 'Unidades Asistenciales (deprecated)'},
        ),
    ]
