# Generated by Django 6.0.5 on 2026-05-07 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_estimada', models.DateField()),
                ('fecha_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Hito',
                'verbose_name_plural': 'Hitos',
                'ordering': ['fecha_estimada'],
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('objetivo', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('planificado', 'Planificado'), ('activo', 'Activo'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='planificado', max_length=20)),
                ('capacidad_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Sprint',
                'verbose_name_plural': 'Sprints',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
