# Generated by Django 6.0.5 on 2026-05-07 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='espaciotrabajo',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='miembroespacio',
            name='espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.espaciotrabajo'),
        ),
        migrations.AddField(
            model_name='miembroespacio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='espaciotrabajo',
            name='miembros',
            field=models.ManyToManyField(related_name='espacios', through='espacios.MiembroEspacio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='miembroespacio',
            unique_together={('espacio', 'usuario')},
        ),
    ]
