# Generated by Django 6.0.5 on 2026-05-07 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembroespacio',
            name='espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros_espacio', to='espacios.espaciotrabajo'),
        ),
    ]
