# Generated by Django 6.0.5 on 2026-05-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnaTablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#6b7280', max_length=7)),
                ('limite_tareas', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Columna del Tablero',
                'verbose_name_plural': 'Columnas del Tablero',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('kanban', 'Kanban'), ('scrum', 'Scrum'), ('personal', 'Personal')], default='kanban', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tablero',
                'verbose_name_plural': 'Tableros',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
