# Generated by Django 6.0.5 on 2026-05-07 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_initial'),
        ('tableros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tablero',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableros_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tablero',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableros', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='columnatablero',
            name='tablero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columnas', to='tableros.tablero'),
        ),
    ]
