# Generated by Django 6.0.5 on 2026-05-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creacion', 'Creación'), ('actualizacion', 'Actualización'), ('eliminacion', 'Eliminación'), ('comentario', 'Comentario'), ('movimiento', 'Movimiento'), ('asignacion', 'Asignación')], max_length=20)),
                ('descripcion', models.TextField()),
                ('metadatos', models.JSONField(blank=True, default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-fecha'],
            },
        ),
    ]
