# Generated by Django 6.0.5 on 2026-05-07 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_initial'),
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='tareas.tarea'),
        ),
    ]
