# Generated by Django 6.0.5 on 2026-05-08 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_initial'),
        ('tareas', '0003_tarea_latitud_tarea_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='tareas.tarea'),
        ),
    ]
