# Generated by Django 6.0.5 on 2026-05-07 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_initial'),
        ('sprints', '0001_initial'),
        ('tableros', '0002_initial'),
        ('tareas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adjunto',
            name='subido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tareas.checklist'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='subtarea',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarea',
            name='columna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='tableros.columnatablero'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarea',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='tareas', to='tareas.etiqueta'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarea',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='sprints.sprint'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='tablero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='tableros.tablero'),
        ),
        migrations.AddField(
            model_name='subtarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='tareas.tarea'),
        ),
        migrations.AddField(
            model_name='dependenciatarea',
            name='tarea_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias_destino', to='tareas.tarea'),
        ),
        migrations.AddField(
            model_name='dependenciatarea',
            name='tarea_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias_origen', to='tareas.tarea'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tareas.tarea'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='tareas.tarea'),
        ),
        migrations.AddField(
            model_name='adjunto',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='tareas.tarea'),
        ),
        migrations.AlterUniqueTogether(
            name='etiqueta',
            unique_together={('nombre', 'proyecto')},
        ),
        migrations.AlterUniqueTogether(
            name='dependenciatarea',
            unique_together={('tarea_origen', 'tarea_destino')},
        ),
    ]
