# Generated by Django 6.0.5 on 2026-05-11 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0012_ua_alter_unidad_options'),
        ('tareas', '0003_tarea_latitud_tarea_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='ua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='proyectos.ua'),
        ),
    ]
